<?php

namespace Database\Seeders;

use App\Models\RbaAccount;
use Illuminate\Database\Seeder;

class RbaAccountSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $accounts = [
            // BELANJA OPERASI
            [
                'account_code' => '1.1.2.1.1',
                'account_name' => 'Belanja bahan habis pakai material kesehatan',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 250000000,
                'remaining_budget' => 250000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.2.1',
                'account_name' => 'Belanja obat generik',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 500000000,
                'remaining_budget' => 500000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.2.2',
                'account_name' => 'Belanja obat non generik',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 350000000,
                'remaining_budget' => 350000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.3',
                'account_name' => 'Belanja bahan habis pakai material laboratorium',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 180000000,
                'remaining_budget' => 180000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.4',
                'account_name' => 'Belanja radiologi',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 45000000,
                'remaining_budget' => 45000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.5',
                'account_name' => 'Belanja bahan habis pakai material laundry',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 65000000,
                'remaining_budget' => 65000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.6',
                'account_name' => 'Belanja bahan habis pakai material Sterilisasi',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 55000000,
                'remaining_budget' => 55000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.7',
                'account_name' => 'Belanja bahan habis pakai psikologi/psikometri',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 30000000,
                'remaining_budget' => 30000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.8',
                'account_name' => 'Belanja Bahan Bakar Minyak/Gas',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 80000000,
                'remaining_budget' => 80000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.9',
                'account_name' => 'Belanja SIM RS',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 120000000,
                'remaining_budget' => 120000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.10',
                'account_name' => 'Belanja cetak RS',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 40000000,
                'remaining_budget' => 40000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.11',
                'account_name' => 'Belanja makanan dan minuman pasien',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 300000000,
                'remaining_budget' => 300000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.12',
                'account_name' => 'Belanja pemeliharaan rutin/berkala rumah sakit',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 150000000,
                'remaining_budget' => 150000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.13',
                'account_name' => 'Belanja pemeliharaan rutin/berkala alat-alat kesehatan',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 90000000,
                'remaining_budget' => 90000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.14',
                'account_name' => 'Belanja Bahan Habis Pakai dan Kelengkapan Rehabilitasi Medik',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 35000000,
                'remaining_budget' => 35000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.15',
                'account_name' => 'Belanja jasa pelayanan Rumah Sakit',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 750000000,
                'remaining_budget' => 750000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.16',
                'account_name' => 'Belanja jasa kantor dan pelayanan rumah sakit',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 60000000,
                'remaining_budget' => 60000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.17',
                'account_name' => 'Belanja jasa kegiatan urusan kesehatan dan non kesehatan',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 400000000,
                'remaining_budget' => 400000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.18',
                'account_name' => 'Belanja jasa pelayanan rujukan',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 50000000,
                'remaining_budget' => 50000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.19',
                'account_name' => 'Belanja Jasa administrasi bank',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 15000000,
                'remaining_budget' => 15000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.20',
                'account_name' => 'Belanja Makan dan Minum',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 45000000,
                'remaining_budget' => 45000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.21',
                'account_name' => 'Belanja Kelengkapan Pasien',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 50000000,
                'remaining_budget' => 50000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.22',
                'account_name' => 'Belanja Peralatan Kebersihan dan Bahan Pembersih',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 60000000,
                'remaining_budget' => 60000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.23',
                'account_name' => 'Belanja Baju Pasien',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 35000000,
                'remaining_budget' => 35000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.24',
                'account_name' => 'Belanja matras/kasur pasien',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 40000000,
                'remaining_budget' => 40000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.25',
                'account_name' => 'Belanja Jasa Akuntan Publik',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 50000000,
                'remaining_budget' => 50000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.26',
                'account_name' => 'Belanja Bahan Habis Pakai Material Gigi',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 30000000,
                'remaining_budget' => 30000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.27',
                'account_name' => 'Belanja Bahan Habis Pakai dan Kelengkapan Rehabilitasi Psikososial',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 75000000,
                'remaining_budget' => 75000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.28',
                'account_name' => 'Belanja Kelengkapan Pelayanan',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 45000000,
                'remaining_budget' => 45000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.29',
                'account_name' => 'Belanja pemeliharaan rutin/berkala Peralatan dan Perlengkapan rumah sakit',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 85000000,
                'remaining_budget' => 85000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.30',
                'account_name' => 'Belanja jasa kesehatan lingkungan RS',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 95000000,
                'remaining_budget' => 95000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.31',
                'account_name' => 'Belanja Pemulangan Pasien',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 25000000,
                'remaining_budget' => 25000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.32',
                'account_name' => 'Belanja Jasa Kontribusi & Perjalanan Dinas Pelatihan',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 60000000,
                'remaining_budget' => 60000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.33',
                'account_name' => 'Belanja Promosi Kesehatan RS',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 30000000,
                'remaining_budget' => 30000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.34',
                'account_name' => 'Belanja Akreditasi RS',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 100000000,
                'remaining_budget' => 100000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.35',
                'account_name' => 'Belanja Peralatan & Perlengkapan Pendukung RS',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 40000000,
                'remaining_budget' => 40000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '5.1.02.01.01.0024',
                'account_name' => 'Belanja Alat Tulis Kantor (ATK)',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 50000000,
                'remaining_budget' => 50000000,
                'spent_budget' => 0,
            ],

            // BELANJA MODAL
            [
                'account_code' => '1.2.02.05.01',
                'account_name' => 'Belanja Modal Peralatan Medis & Keperawatan',
                'kategori_belanja' => 'Modal',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 450000000,
                'remaining_budget' => 450000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.2.02.10.01',
                'account_name' => 'Belanja Modal Komputer & Jaringan',
                'kategori_belanja' => 'Modal',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 120000000,
                'remaining_budget' => 120000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.2.02.15.01',
                'account_name' => 'Belanja Modal Peralatan dan Mesin Lainnya',
                'kategori_belanja' => 'Modal',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 80000000,
                'remaining_budget' => 80000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.2.03.01.01',
                'account_name' => 'Belanja Modal Gedung dan Bangunan RS',
                'kategori_belanja' => 'Modal',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 500000000,
                'remaining_budget' => 500000000,
                'spent_budget' => 0,
            ],
        ];

        foreach ($accounts as $acc) {
            RbaAccount::updateOrCreate(
                ['account_code' => $acc['account_code']],
                $acc
            );
        }
    }
}
