<?php

namespace Database\Seeders;

use App\Models\RbaAccount;
use Illuminate\Database\Seeder;

class RbaAccountSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $rbaData = [
            ['account_code' => '1.1', 'account_name' => 'BELANJA OPERASI', 'kategori_belanja' => 'Operasi', 'parent_code' => null],
            ['account_code' => '1.1.1', 'account_name' => 'Belanja Pegawai', 'kategori_belanja' => 'Operasi', 'parent_code' => '1.1'],
            ['account_code' => '1.1.2', 'account_name' => 'Belanja Barang dan Jasa', 'kategori_belanja' => 'Operasi', 'parent_code' => '1.1'],
            ['account_code' => '1.1.2.1', 'account_name' => 'Belanja Barang dan jasa BLUD', 'kategori_belanja' => 'Operasi', 'parent_code' => '1.1.2'],
            ['account_code' => '1.1.2.1.2', 'account_name' => 'Belanja obat-obatan', 'kategori_belanja' => 'Operasi', 'parent_code' => '1.1.2.1'],
            ['account_code' => '1.1.2.1.12', 'account_name' => 'Belanja pemeliharaan rutin RS', 'kategori_belanja' => 'Operasi', 'parent_code' => '1.1.2.1'],
            ['account_code' => '1.2', 'account_name' => 'BELANJA MODAL', 'kategori_belanja' => 'Modal', 'parent_code' => null],
            ['account_code' => '1.2.1', 'account_name' => 'Belanja Modal BLUD', 'kategori_belanja' => 'Modal', 'parent_code' => '1.2'],
            ['account_code' => '1.2.1.3.1', 'account_name' => 'Belanja Modal Gedung dan Bangunan', 'kategori_belanja' => 'Modal', 'parent_code' => '1.2.1.3'],
        ];

        foreach ($rbaData as $item) {
            RbaAccount::updateOrCreate(
                ['account_code' => $item['account_code']],
                [
                    'account_name' => $item['account_name'],
                    'kategori_belanja' => $item['kategori_belanja'],
                    'parent_code' => $item['parent_code'] ?? null,
                    'year' => 2026,
                    'period_year' => 2026,
                    'funding_source' => 'BLUD',
                    'sumber_dana' => 'BLUD',
                    'budget_after_revision' => 100000000,
                    'total_budget' => 100000000,
                    'remaining_budget' => 100000000,
                    'spent_budget' => 0,
                ]
            );
        }

        $accounts = [
            // ==========================================
            // 1.1 BELANJA OPERASI
            // ==========================================
            [
                'account_code' => '1.1.1.1',
                'parent_code' => '1.1.1',
                'account_name' => 'Belanja Pegawai BLUD',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 0,
                'remaining_budget' => 0,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1',
                'parent_code' => '1.1.2',
                'account_name' => 'Belanja Barang dan jasa BLUD',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 500000000,
                'remaining_budget' => 500000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.1',
                'parent_code' => '1.1.2.1',
                'account_name' => 'Belanja bahan habis pakai material kesehatan',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 366228500,
                'remaining_budget' => 366228500,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.2',
                'parent_code' => '1.1.2.1',
                'account_name' => 'Belanja obat-obatan',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 2320436690,
                'remaining_budget' => 2320436690,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.2.1',
                'parent_code' => '1.1.2.1.2',
                'account_name' => 'Belanja obat generik',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 1505535960,
                'remaining_budget' => 1505535960,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.2.2',
                'parent_code' => '1.1.2.1.2',
                'account_name' => 'Belanja obat non generik',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 814900730,
                'remaining_budget' => 814900730,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.3',
                'parent_code' => '1.1.2.1',
                'account_name' => 'Belanja bahan habis pakai material laboratorium',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 955151302,
                'remaining_budget' => 955151302,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.4',
                'parent_code' => '1.1.2.1',
                'account_name' => 'Belanja radiologi',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 5500000,
                'remaining_budget' => 5500000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.5',
                'parent_code' => '1.1.2.1',
                'account_name' => 'Belanja bahan habis pakai material laundry',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 108457648,
                'remaining_budget' => 108457648,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.6',
                'parent_code' => '1.1.2.1',
                'account_name' => 'Belanja bahan habis pakai material Sterilisasi',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 41875000,
                'remaining_budget' => 41875000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.7',
                'parent_code' => '1.1.2.1',
                'account_name' => 'Belanja bahan habis pakai psikologi/psikometri',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 10000000,
                'remaining_budget' => 10000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.8',
                'parent_code' => '1.1.2.1',
                'account_name' => 'Belanja Bahan Bakar Minyak/Gas',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 5500000,
                'remaining_budget' => 5500000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.9',
                'parent_code' => '1.1.2.1',
                'account_name' => 'Belanja SIM RS',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 90000000,
                'remaining_budget' => 90000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.10',
                'parent_code' => '1.1.2.1',
                'account_name' => 'Belanja cetak RS',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 66999200,
                'remaining_budget' => 66999200,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.11',
                'parent_code' => '1.1.2.1',
                'account_name' => 'Belanja makanan dan minuman pasien',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 146751400,
                'remaining_budget' => 146751400,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.12',
                'parent_code' => '1.1.2.1',
                'account_name' => 'Belanja pemeliharaan rutin/berkala rumah sakit',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 1707620000,
                'remaining_budget' => 1707620000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.13',
                'parent_code' => '1.1.2.1',
                'account_name' => 'Belanja pemeliharaan rutin/berkala alat-alat kesehatan',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 287000000,
                'remaining_budget' => 287000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.14',
                'parent_code' => '1.1.2.1',
                'account_name' => 'Belanja Bahan Habis Pakai dan Kelengkapan Rehabilitasi Medik',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 20000000,
                'remaining_budget' => 20000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.15',
                'parent_code' => '1.1.2.1',
                'account_name' => 'Belanja jasa pelayanan Rumah Sakit',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 12138814388,
                'remaining_budget' => 12138814388,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.16',
                'parent_code' => '1.1.2.1',
                'account_name' => 'Belanja jasa kantor dan pelayanan rumah sakit',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 616720000,
                'remaining_budget' => 616720000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.17',
                'parent_code' => '1.1.2.1',
                'account_name' => 'Belanja jasa kegiatan urusan kesehatan dan non kesehatan',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 2703900000,
                'remaining_budget' => 2703900000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.17.1',
                'parent_code' => '1.1.2.1.17',
                'account_name' => 'Jasa Tenaga Dokter dan MOU',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 1740000000,
                'remaining_budget' => 1740000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.17.2',
                'parent_code' => '1.1.2.1.17',
                'account_name' => 'Jasa Tenaga Honor BLUD',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 678000000,
                'remaining_budget' => 678000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.17.3',
                'parent_code' => '1.1.2.1.17',
                'account_name' => 'Jasa Dewan Pengawas',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 207600000,
                'remaining_budget' => 207600000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.17.4',
                'parent_code' => '1.1.2.1.17',
                'account_name' => 'BPJS Ketenagakerjaan Non ASN',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 15300000,
                'remaining_budget' => 15300000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.17.5',
                'parent_code' => '1.1.2.1.17',
                'account_name' => 'Biaya Gaji 13 dan THR Non ASN',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 63000000,
                'remaining_budget' => 63000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.17.6',
                'parent_code' => '1.1.2.1.17',
                'account_name' => 'Biaya Gaji 13 dan THR PPPK Paruh Waktu',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 82500000,
                'remaining_budget' => 82500000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.18',
                'parent_code' => '1.1.2.1',
                'account_name' => 'Belanja jasa pelayanan rujukan',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 87842000,
                'remaining_budget' => 87842000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.19',
                'parent_code' => '1.1.2.1',
                'account_name' => 'Belanja Jasa administrasi bank',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 5000000,
                'remaining_budget' => 5000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.20',
                'parent_code' => '1.1.2.1',
                'account_name' => 'Belanja Makan dan Minum',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 109770000,
                'remaining_budget' => 109770000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.21',
                'parent_code' => '1.1.2.1',
                'account_name' => 'Belanja Kelengkapan Pasien',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 181050000,
                'remaining_budget' => 181050000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.22',
                'parent_code' => '1.1.2.1',
                'account_name' => 'Belanja Peralatan Kebersihan dan Bahan Pembersih',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 99596000,
                'remaining_budget' => 99596000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.23',
                'parent_code' => '1.1.2.1',
                'account_name' => 'Belanja Baju Pasien',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 387500000,
                'remaining_budget' => 387500000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.24',
                'parent_code' => '1.1.2.1',
                'account_name' => 'Belanja matras/kasur pasien',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 75000000,
                'remaining_budget' => 75000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.25',
                'parent_code' => '1.1.2.1',
                'account_name' => 'Belanja Jasa Akuntan Publik',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 75000000,
                'remaining_budget' => 75000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.26',
                'parent_code' => '1.1.2.1',
                'account_name' => 'Belanja Bahan Habis Pakai Material Gigi',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 10000000,
                'remaining_budget' => 10000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.27',
                'parent_code' => '1.1.2.1',
                'account_name' => 'Belanja Bahan Habis Pakai dan Kelengkapan Rehabilitasi Psikososial',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 53491000,
                'remaining_budget' => 53491000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.28',
                'parent_code' => '1.1.2.1',
                'account_name' => 'Belanja Kelengkapan Pelayanan',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 105387000,
                'remaining_budget' => 105387000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.29',
                'parent_code' => '1.1.2.1',
                'account_name' => 'Belanja pemeliharaan rutin/berkala Peralatan dan Perlengkapan rumah sakit',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 692600000,
                'remaining_budget' => 692600000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.30',
                'parent_code' => '1.1.2.1',
                'account_name' => 'Belanja jasa kesehatan lingkungan RS',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 693800000,
                'remaining_budget' => 693800000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.31',
                'parent_code' => '1.1.2.1',
                'account_name' => 'Belanja Pemulangan Pasien',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 50000000,
                'remaining_budget' => 50000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.32',
                'parent_code' => '1.1.2.1',
                'account_name' => 'Belanja Jasa Kontribusi & Perjalanan Dinas Pelatihan',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 231592000,
                'remaining_budget' => 231592000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.33',
                'parent_code' => '1.1.2.1',
                'account_name' => 'Belanja Promosi Kesehatan RS',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 72533000,
                'remaining_budget' => 72533000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.34',
                'parent_code' => '1.1.2.1',
                'account_name' => 'Belanja Akreditasi RS',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 188030000,
                'remaining_budget' => 188030000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.1.2.1.35',
                'parent_code' => '1.1.2.1',
                'account_name' => 'Belanja Peralatan & Perlengkapan Pendukung RS',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 9045000,
                'remaining_budget' => 9045000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '5.1.02.01.01.0024',
                'parent_code' => '1.1.2.1',
                'account_name' => 'Belanja Alat Tulis Kantor (ATK)',
                'kategori_belanja' => 'Operasi',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 50000000,
                'remaining_budget' => 50000000,
                'spent_budget' => 0,
            ],

            // ==========================================
            // 1.2 BELANJA MODAL
            // ==========================================
            [
                'account_code' => '1.2.1.1',
                'parent_code' => '1.2.1',
                'account_name' => 'Belanja Tanah',
                'kategori_belanja' => 'Modal',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 0,
                'remaining_budget' => 0,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.2.1.2',
                'parent_code' => '1.2.1',
                'account_name' => 'Belanja Peralatan dan Mesin',
                'kategori_belanja' => 'Modal',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 500000000,
                'remaining_budget' => 500000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.2.1.2.1',
                'parent_code' => '1.2.1.2',
                'account_name' => 'Belanja Alat Kesehatan RS',
                'kategori_belanja' => 'Modal',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 278004200,
                'remaining_budget' => 278004200,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.2.1.2.2',
                'parent_code' => '1.2.1.2',
                'account_name' => 'Belanja peralatan dan perlengkapan rumah sakit',
                'kategori_belanja' => 'Modal',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 221995800,
                'remaining_budget' => 221995800,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.2.1.3',
                'parent_code' => '1.2.1',
                'account_name' => 'Belanja Gedung dan Bangunan',
                'kategori_belanja' => 'Modal',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 500000000,
                'remaining_budget' => 500000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.2.1.3.1',
                'parent_code' => '1.2.1.3',
                'account_name' => 'Belanja Modal Gedung dan Bangunan',
                'kategori_belanja' => 'Modal',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 500000000,
                'remaining_budget' => 500000000,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.2.1.4',
                'parent_code' => '1.2.1',
                'account_name' => 'Belanja Jalan/ Irigasi Dan jaringan',
                'kategori_belanja' => 'Modal',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 0,
                'remaining_budget' => 0,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.2.1.5',
                'parent_code' => '1.2.1',
                'account_name' => 'Belanja Aset tetap lainnya',
                'kategori_belanja' => 'Modal',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 0,
                'remaining_budget' => 0,
                'spent_budget' => 0,
            ],
            [
                'account_code' => '1.2.1.6',
                'parent_code' => '1.2.1',
                'account_name' => 'Belanja Aset lainnya',
                'kategori_belanja' => 'Modal',
                'sumber_dana' => 'BLUD',
                'period_year' => 2026,
                'total_budget' => 0,
                'remaining_budget' => 0,
                'spent_budget' => 0,
            ],
        ];

        foreach ($accounts as $acc) {
            RbaAccount::updateOrCreate(
                ['account_code' => $acc['account_code']],
                $acc
            );
        }

        // Migrate any items/requisitions pointing to legacy 1.2.02 codes
        $mapping = [
            '1.2.02.05.01' => '1.2.1.2.1',
            '1.2.02.10.01' => '1.2.1.2.2',
            '1.2.02.15.01' => '1.2.1.2.2',
            '1.2.03.01.01' => '1.2.1.3.1',
        ];

        foreach ($mapping as $oldCode => $newCode) {
            $oldAcc = RbaAccount::where('account_code', $oldCode)->first();
            $newAcc = RbaAccount::where('account_code', $newCode)->first();
            if ($oldAcc && $newAcc) {
                \App\Models\Item::where('rba_account_id', $oldAcc->id)->update(['rba_account_id' => $newAcc->id]);
                \App\Models\Requisition::where('rba_account_id', $oldAcc->id)->update(['rba_account_id' => $newAcc->id]);
                \App\Models\Requisition::where('rba_account_id', $oldAcc->id)->update(['rba_account_id' => $newAcc->id]);
            }
        }
    }
}
